export const CART_ADD_TO_CART = 'CART_ADD_TO_CART';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING = 'CART_SAVE_SHIPPING';
export const CART_SAVE_PAYMENT ='CART_SAVE_PAYMENT';